kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  # these labels are deployment related labels
  labels:
    component: frontend
    tier: web
spec:
  replicas: {{ .Values.Deployment.replicas }}
  selector:
    matchLabels:
      component: frontend
      tier: web
  # pod definition
  template:
    metadata:
      labels:
        component: frontend
        tier: web
    spec:
      containers:
      - name: frontend
        image: nginx:{{ .Values.Deployment.imageVersion }}
        ports:
        - containerPort: 80
        imagePullPolicy: Always