apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  # type: LoadBalancer
  selector:
    component: frontend
    tier: web
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: {{ .Values.configmap.port }} #target-port means the port on which the application is running(container port)